"""
correction_loop.py
------------------
LangChain-backed SQL correction loop.

This module repairs invalid SQL generated by the LLM.
It is used when validation fails or PostgreSQL execution raises an error.
"""

import inspect
import re

from practice.sql_validator import validate_sql as validate_read_only_sql


def clean_sql_response(response_text):
    if not response_text:
        raise ValueError("LLM returned empty correction response")

    sql = response_text.strip()
    sql = re.sub(r"```sql", "", sql, flags=re.IGNORECASE)
    sql = sql.replace("```", "").strip()

    match = re.search(
        r"\b(WITH|SELECT)\b[\s\S]*?;",
        sql,
        flags=re.IGNORECASE
    )

    if match:
        cleaned_sql = match.group(0).strip()
    else:
        lines = sql.splitlines()
        collecting = False
        parts = []

        for line in lines:
            clean_line = line.strip()
            upper_line = clean_line.upper()

            if upper_line.startswith("SELECT") or upper_line.startswith("WITH"):
                collecting = True

            if collecting:
                parts.append(clean_line)

        cleaned_sql = " ".join(parts) if parts else sql

    cleaned_sql = re.sub(r"\s+", " ", cleaned_sql).strip()

    if cleaned_sql and not cleaned_sql.endswith(";"):
        cleaned_sql += ";"

    return cleaned_sql


def validate_corrected_sql(sql, allowed_tables=None):
    is_valid, message = validate_read_only_sql(sql, allowed_tables=allowed_tables)

    if not is_valid:
        raise ValueError(message)

    return True


def _safe_identifier(identifier):
    if not isinstance(identifier, str) or not re.fullmatch(
        r"[A-Za-z_][A-Za-z0-9_$]*(?:\.[A-Za-z_][A-Za-z0-9_$]*)?",
        identifier.strip(),
    ):
        raise ValueError("Dataset schema contains an unsafe SQL identifier")
    return identifier.strip().lower()


def _dataset_schema_lines(dataset_columns):
    if not dataset_columns:
        return ["- Schema metadata unavailable; do not invent columns"]

    lines = []
    for item in dataset_columns:
        if isinstance(item, dict):
            name = item.get("name")
            data_type = item.get("type", "unknown")
        else:
            name = item
            data_type = "unknown"
        name = _safe_identifier(name)
        if "." in name:
            raise ValueError("Dataset column identifiers cannot be schema-qualified")
        safe_type = re.sub(r"[^A-Za-z0-9_ (),.\[\]+-]", "", str(data_type))[:80]
        lines.append(f"- {name} ({safe_type or 'unknown'})")
    return lines


def _fallback_prompt(
    question,
    wrong_sql,
    error_message,
    dataset_table=None,
    dataset_columns=None,
    allowed_tables=None,
):
    if dataset_table:
        dataset_table = _safe_identifier(dataset_table)
        schema = "\n".join(_dataset_schema_lines(dataset_columns))
        allowed_text = ", ".join(allowed_tables or [dataset_table])
        return f"""
You are an expert PostgreSQL correction assistant for one uploaded dataset.

User question:
{question}

Wrong SQL:
{wrong_sql}

Safe database error:
{error_message}

Selected physical table: {dataset_table}
Available columns:
{schema}
Exact allowed physical tables: {allowed_text}

Rules:
- Return only one corrected SQL statement ending with one semicolon.
- Use only SELECT or WITH ... SELECT.
- Read only from the selected physical table and the listed columns.
- CTE aliases may be used, but no other physical table or schema may be used.
- Do not use comments, quoted identifiers, dollar quoting, or multiple statements.
- Do not use INSERT, UPDATE, DELETE, DROP, ALTER, TRUNCATE, CREATE,
  REPLACE, MERGE, GRANT, REVOKE, COPY, CALL, DO, or transaction commands.
- Do not use filesystem, network, dblink, large-object, or administrative functions.
- Do not explain anything.
"""

    return f"""
You are an expert PostgreSQL SQL correction assistant.

User question:
{question}

Wrong SQL:
{wrong_sql}

Error message:
{error_message}

Database schema:
- customers(customer_id, country, signup_date)
- products(product_id, product_name, category)
- orders(order_id, customer_id, order_date, status)
- order_items(order_id, product_id, quantity, price)

Rules:
- Return only corrected SQL.
- Use PostgreSQL syntax.
- Use only SELECT or WITH SELECT queries.
- Do not explain anything and do not include SQL comments.
- Do not use INSERT, UPDATE, DELETE, DROP, ALTER, TRUNCATE, CREATE,
  REPLACE, MERGE, GRANT, REVOKE, COPY, CALL, DO, or transaction commands.
- Do not use filesystem, network, dblink, large-object, or administrative functions.
- End the SQL with one semicolon.
"""


def fix_sql(
    generator,
    question,
    wrong_sql,
    error_message,
    allowed_tables=None,
    dataset_table=None,
    dataset_columns=None,
):
    """
    Fix SQL using LangChain.

    If SQLGenerator has fix_sql_with_langchain(), we use it.
    Otherwise, we fall back to call_gemini_raw() for backward compatibility.
    """
    try:
        if isinstance(allowed_tables, str):
            normalized_allowed = [_safe_identifier(allowed_tables)]
        elif allowed_tables is None:
            normalized_allowed = None
        else:
            normalized_allowed = [_safe_identifier(item) for item in allowed_tables]

        if dataset_table is None and normalized_allowed and len(normalized_allowed) == 1:
            # A one-table allowlist is enough to keep older uploaded-dataset
            # callers scoped even before they add the explicit keyword.
            dataset_table = normalized_allowed[0]
        elif dataset_table is not None:
            dataset_table = _safe_identifier(dataset_table)

        if dataset_table is not None:
            expected_allowed = [dataset_table]
            if normalized_allowed is None:
                normalized_allowed = expected_allowed
            elif normalized_allowed != expected_allowed:
                raise ValueError(
                    "Uploaded dataset correction requires exactly the selected table in allowed_tables"
                )

        if hasattr(generator, "fix_sql_with_langchain"):
            method = generator.fix_sql_with_langchain
            signature = inspect.signature(method)
            accepts_kwargs = any(
                parameter.kind == inspect.Parameter.VAR_KEYWORD
                for parameter in signature.parameters.values()
            )
            context = {
                "dataset_table": dataset_table,
                "dataset_columns": dataset_columns,
                "allowed_tables": normalized_allowed,
            }
            supported_context = {
                key: value
                for key, value in context.items()
                if accepts_kwargs or key in signature.parameters
            }
            corrected_sql = method(
                question=question,
                wrong_sql=wrong_sql,
                error_message=error_message,
                **supported_context,
            )
        else:
            correction_prompt = _fallback_prompt(
                question=question,
                wrong_sql=wrong_sql,
                error_message=error_message,
                dataset_table=dataset_table,
                dataset_columns=dataset_columns,
                allowed_tables=normalized_allowed,
            )
            corrected_sql = generator.call_gemini_raw(correction_prompt)
            corrected_sql = clean_sql_response(corrected_sql)

        validate_corrected_sql(corrected_sql, allowed_tables=normalized_allowed)
        return corrected_sql

    except Exception as exc:
        raise Exception(f"SQL correction failed: {exc}")
